### ISSUE TITLE
Error in older versions of Racket

### ISSUE THREAD

**Issue by countvajhula** [Metaxal/quickscript-extra#23]
Hi again! Just reporting this error, in case you're interested in fixing it. I listed `quickscript-extra` as a doc dependency in the `qi` repo (temporarily - until I move the docs to a separate sub-collection as we discussed in countvajhula/qi#7) and when I run the GitHub Actions test matrix it fails on versions older than 8.1.

[Error on <=7.9](https://github.com/countvajhula/qi/runs/4219679426?check_suite_focus=true#step:4:329) [for this one, I've been using `version-case` to [alias the new name](https://github.com/countvajhula/relation/blob/575909d7dc7cfdf713fe40a93655f268943e82a3/function/syntax.rkt#L17-L19) to the older name]

[Error on 8.0](https://github.com/countvajhula/qi/runs/4242594024?check_suite_focus=true#step:4:428)

This issue would only affect qi-docs after I make the transition, but it might affect other libraries depending on quickscript-extra so that they would only support >= 8.1.

(Btw, in case you're interested in using Github Actions to do this kind of matrix testing, I wrote a [blog post](https://countvajhula.com/2021/05/22/migrating-your-racket-project-from-travis-to-github-actions/) some time ago on how to set it up)

**Comment by spdegabrielle** [comment]
I think this resolves the define
https://github.com/Metaxal/search-list-box/pull/5

```
/home/runner/.racket/7.8/pkgs/search-list-box/main.rkt:55:1: define-syntax-parse-rule: unbound identifier
330  in: define-syntax-parse-rule
331  compilation context...:
332   /home/runner/.racket/7.8/pkgs/search-list-box/main.rkt
333   /home/runner/.racket/7.8/pkgs/quickscript-extra/scripts/bookmarks.rkt
```

**Comment by Metaxal** [comment]
Should be fixed via https://github.com/Metaxal/search-list-box/commit/11103aaddf3410127a8cbcb694e78c53f62444ca

**Comment by Metaxal** [comment]
Thanks for the report @countvajhula !

**Comment by countvajhula** [comment]
@Metaxal There's still the error in 8.0:

<img width="786" alt="Screen Shot 2021-11-20 at 9 00 19 AM" src="https://user-images.githubusercontent.com/401668/142734825-ca17fd2b-7446-4496-9de3-909019de0204.png">

Any idea about that one?

**Comment by Metaxal** [comment]
Yes that one does require a newer version of Racket (8.1 I think?), since
Quickscript is bundled with DrRacket and quickscript/utils was added in
February.

I guess i could add a version check in quickscript-extra. Is that important
to fix?

**Comment by spdegabrielle** [comment]
I'd suggest that while code used in production needs to support a reasonable amount of backward compatibility, code used in the act of developing software does not have the same requirements.

I would not put a lot of effort into supporting old versions of Racket.

**Comment by countvajhula** [comment]
All this makes sense. I'm wondering how I should handle the dependency in Qi. qi depends on qi-doc which depends on quickscript-extra. If quickscript-extra is >= 8.1, then that would mean Qi would need to be >= 8.1 as well.

The reason for the quickscript-extra dependency is simply that I'm using this: `@other-doc['(lib "quickscript-extra/scribblings/quickscript-extra.scrbl")]`. Ideally it seems like `@other-doc` shouldn't introduce a dependency and should just "link at runtime,"
but I could just eliminate the dependency by using `@hyperlink` here instead, unless there's a better way.

**Comment by Metaxal** [comment]
Maybe you can link to the online docs: https://docs.racket-lang.org/quickscript-extra/
