### ISSUE TITLE
Utils -> Color Chooser could default to non-white

### ISSUE THREAD

**Issue by maueroats** [Metaxal/quickscript-extra#25]
The default color picker has H=0, S=0, V=100.
Choosing H=0, S=100, V=100 for the default would make it possible to alter the H value (only) to get different colors. 

Newbie confusion: "rotating the color wheel" = changing the H selection doesn't change RGB values because with S=0, V=100 everything is white.

This will be followed by a pr for [color-chooser-rkt](https://github.com/Metaxal/quickscript-extra/blob/24e12e387bca5fe7da9ae573f2758e6003defe91/scripts/color-chooser.rkt#L27).

**Comment by Metaxal** [comment]
Fixed by #26

**Comment by Metaxal** [comment]
and thanks for the report!
